[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"

# Or alternatively, specify which keys to ignore:
# [build.environment]
#   SECRETS_SCAN_OMIT_KEYS = "VITE_SECRET_PASSWORD" 